# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/howard/work/LeoLibraryHelper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/howard/work/LeoLibraryHelper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/howard/work/LeoLibraryHelper/CMakeFiles /home/howard/work/LeoLibraryHelper/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/howard/work/LeoLibraryHelper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named autoReservate

# Build rule for target.
autoReservate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autoReservate
.PHONY : autoReservate

# fast build rule for target.
autoReservate/fast:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/build
.PHONY : autoReservate/fast

src/autoReservate/httpRequest.o: src/autoReservate/httpRequest.cc.o

.PHONY : src/autoReservate/httpRequest.o

# target to build an object file
src/autoReservate/httpRequest.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/httpRequest.cc.o
.PHONY : src/autoReservate/httpRequest.cc.o

src/autoReservate/httpRequest.i: src/autoReservate/httpRequest.cc.i

.PHONY : src/autoReservate/httpRequest.i

# target to preprocess a source file
src/autoReservate/httpRequest.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/httpRequest.cc.i
.PHONY : src/autoReservate/httpRequest.cc.i

src/autoReservate/httpRequest.s: src/autoReservate/httpRequest.cc.s

.PHONY : src/autoReservate/httpRequest.s

# target to generate assembly for a file
src/autoReservate/httpRequest.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/httpRequest.cc.s
.PHONY : src/autoReservate/httpRequest.cc.s

src/autoReservate/leoApi.o: src/autoReservate/leoApi.cc.o

.PHONY : src/autoReservate/leoApi.o

# target to build an object file
src/autoReservate/leoApi.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/leoApi.cc.o
.PHONY : src/autoReservate/leoApi.cc.o

src/autoReservate/leoApi.i: src/autoReservate/leoApi.cc.i

.PHONY : src/autoReservate/leoApi.i

# target to preprocess a source file
src/autoReservate/leoApi.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/leoApi.cc.i
.PHONY : src/autoReservate/leoApi.cc.i

src/autoReservate/leoApi.s: src/autoReservate/leoApi.cc.s

.PHONY : src/autoReservate/leoApi.s

# target to generate assembly for a file
src/autoReservate/leoApi.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/leoApi.cc.s
.PHONY : src/autoReservate/leoApi.cc.s

src/autoReservate/libcurl.o: src/autoReservate/libcurl.cc.o

.PHONY : src/autoReservate/libcurl.o

# target to build an object file
src/autoReservate/libcurl.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/libcurl.cc.o
.PHONY : src/autoReservate/libcurl.cc.o

src/autoReservate/libcurl.i: src/autoReservate/libcurl.cc.i

.PHONY : src/autoReservate/libcurl.i

# target to preprocess a source file
src/autoReservate/libcurl.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/libcurl.cc.i
.PHONY : src/autoReservate/libcurl.cc.i

src/autoReservate/libcurl.s: src/autoReservate/libcurl.cc.s

.PHONY : src/autoReservate/libcurl.s

# target to generate assembly for a file
src/autoReservate/libcurl.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/libcurl.cc.s
.PHONY : src/autoReservate/libcurl.cc.s

src/autoReservate/mainReservate.o: src/autoReservate/mainReservate.cc.o

.PHONY : src/autoReservate/mainReservate.o

# target to build an object file
src/autoReservate/mainReservate.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/mainReservate.cc.o
.PHONY : src/autoReservate/mainReservate.cc.o

src/autoReservate/mainReservate.i: src/autoReservate/mainReservate.cc.i

.PHONY : src/autoReservate/mainReservate.i

# target to preprocess a source file
src/autoReservate/mainReservate.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/mainReservate.cc.i
.PHONY : src/autoReservate/mainReservate.cc.i

src/autoReservate/mainReservate.s: src/autoReservate/mainReservate.cc.s

.PHONY : src/autoReservate/mainReservate.s

# target to generate assembly for a file
src/autoReservate/mainReservate.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/mainReservate.cc.s
.PHONY : src/autoReservate/mainReservate.cc.s

src/autoReservate/mainTest.o: src/autoReservate/mainTest.cc.o

.PHONY : src/autoReservate/mainTest.o

# target to build an object file
src/autoReservate/mainTest.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/mainTest.cc.o
.PHONY : src/autoReservate/mainTest.cc.o

src/autoReservate/mainTest.i: src/autoReservate/mainTest.cc.i

.PHONY : src/autoReservate/mainTest.i

# target to preprocess a source file
src/autoReservate/mainTest.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/mainTest.cc.i
.PHONY : src/autoReservate/mainTest.cc.i

src/autoReservate/mainTest.s: src/autoReservate/mainTest.cc.s

.PHONY : src/autoReservate/mainTest.s

# target to generate assembly for a file
src/autoReservate/mainTest.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/mainTest.cc.s
.PHONY : src/autoReservate/mainTest.cc.s

src/autoReservate/stuPool.o: src/autoReservate/stuPool.cc.o

.PHONY : src/autoReservate/stuPool.o

# target to build an object file
src/autoReservate/stuPool.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/stuPool.cc.o
.PHONY : src/autoReservate/stuPool.cc.o

src/autoReservate/stuPool.i: src/autoReservate/stuPool.cc.i

.PHONY : src/autoReservate/stuPool.i

# target to preprocess a source file
src/autoReservate/stuPool.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/stuPool.cc.i
.PHONY : src/autoReservate/stuPool.cc.i

src/autoReservate/stuPool.s: src/autoReservate/stuPool.cc.s

.PHONY : src/autoReservate/stuPool.s

# target to generate assembly for a file
src/autoReservate/stuPool.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/stuPool.cc.s
.PHONY : src/autoReservate/stuPool.cc.s

src/autoReservate/student.o: src/autoReservate/student.cc.o

.PHONY : src/autoReservate/student.o

# target to build an object file
src/autoReservate/student.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/student.cc.o
.PHONY : src/autoReservate/student.cc.o

src/autoReservate/student.i: src/autoReservate/student.cc.i

.PHONY : src/autoReservate/student.i

# target to preprocess a source file
src/autoReservate/student.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/student.cc.i
.PHONY : src/autoReservate/student.cc.i

src/autoReservate/student.s: src/autoReservate/student.cc.s

.PHONY : src/autoReservate/student.s

# target to generate assembly for a file
src/autoReservate/student.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/student.cc.s
.PHONY : src/autoReservate/student.cc.s

src/autoReservate/util.o: src/autoReservate/util.cc.o

.PHONY : src/autoReservate/util.o

# target to build an object file
src/autoReservate/util.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/util.cc.o
.PHONY : src/autoReservate/util.cc.o

src/autoReservate/util.i: src/autoReservate/util.cc.i

.PHONY : src/autoReservate/util.i

# target to preprocess a source file
src/autoReservate/util.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/util.cc.i
.PHONY : src/autoReservate/util.cc.i

src/autoReservate/util.s: src/autoReservate/util.cc.s

.PHONY : src/autoReservate/util.s

# target to generate assembly for a file
src/autoReservate/util.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/autoReservate/util.cc.s
.PHONY : src/autoReservate/util.cc.s

src/publicUtil/redisTool.o: src/publicUtil/redisTool.cc.o

.PHONY : src/publicUtil/redisTool.o

# target to build an object file
src/publicUtil/redisTool.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/publicUtil/redisTool.cc.o
.PHONY : src/publicUtil/redisTool.cc.o

src/publicUtil/redisTool.i: src/publicUtil/redisTool.cc.i

.PHONY : src/publicUtil/redisTool.i

# target to preprocess a source file
src/publicUtil/redisTool.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/publicUtil/redisTool.cc.i
.PHONY : src/publicUtil/redisTool.cc.i

src/publicUtil/redisTool.s: src/publicUtil/redisTool.cc.s

.PHONY : src/publicUtil/redisTool.s

# target to generate assembly for a file
src/publicUtil/redisTool.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/publicUtil/redisTool.cc.s
.PHONY : src/publicUtil/redisTool.cc.s

src/publicUtil/stuInfo.pb.o: src/publicUtil/stuInfo.pb.cc.o

.PHONY : src/publicUtil/stuInfo.pb.o

# target to build an object file
src/publicUtil/stuInfo.pb.cc.o:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/publicUtil/stuInfo.pb.cc.o
.PHONY : src/publicUtil/stuInfo.pb.cc.o

src/publicUtil/stuInfo.pb.i: src/publicUtil/stuInfo.pb.cc.i

.PHONY : src/publicUtil/stuInfo.pb.i

# target to preprocess a source file
src/publicUtil/stuInfo.pb.cc.i:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/publicUtil/stuInfo.pb.cc.i
.PHONY : src/publicUtil/stuInfo.pb.cc.i

src/publicUtil/stuInfo.pb.s: src/publicUtil/stuInfo.pb.cc.s

.PHONY : src/publicUtil/stuInfo.pb.s

# target to generate assembly for a file
src/publicUtil/stuInfo.pb.cc.s:
	$(MAKE) -f CMakeFiles/autoReservate.dir/build.make CMakeFiles/autoReservate.dir/src/publicUtil/stuInfo.pb.cc.s
.PHONY : src/publicUtil/stuInfo.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... autoReservate"
	@echo "... edit_cache"
	@echo "... src/autoReservate/httpRequest.o"
	@echo "... src/autoReservate/httpRequest.i"
	@echo "... src/autoReservate/httpRequest.s"
	@echo "... src/autoReservate/leoApi.o"
	@echo "... src/autoReservate/leoApi.i"
	@echo "... src/autoReservate/leoApi.s"
	@echo "... src/autoReservate/libcurl.o"
	@echo "... src/autoReservate/libcurl.i"
	@echo "... src/autoReservate/libcurl.s"
	@echo "... src/autoReservate/mainReservate.o"
	@echo "... src/autoReservate/mainReservate.i"
	@echo "... src/autoReservate/mainReservate.s"
	@echo "... src/autoReservate/mainTest.o"
	@echo "... src/autoReservate/mainTest.i"
	@echo "... src/autoReservate/mainTest.s"
	@echo "... src/autoReservate/stuPool.o"
	@echo "... src/autoReservate/stuPool.i"
	@echo "... src/autoReservate/stuPool.s"
	@echo "... src/autoReservate/student.o"
	@echo "... src/autoReservate/student.i"
	@echo "... src/autoReservate/student.s"
	@echo "... src/autoReservate/util.o"
	@echo "... src/autoReservate/util.i"
	@echo "... src/autoReservate/util.s"
	@echo "... src/publicUtil/redisTool.o"
	@echo "... src/publicUtil/redisTool.i"
	@echo "... src/publicUtil/redisTool.s"
	@echo "... src/publicUtil/stuInfo.pb.o"
	@echo "... src/publicUtil/stuInfo.pb.i"
	@echo "... src/publicUtil/stuInfo.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

